/**
 * Dumps the Notion schema to SCHEMA.md — the same definitions the provision
 * script writes to Notion, in a form a person (or a chat session) can read
 * without opening the codebase.
 *
 * Usage: npm run schema:doc
 *
 * Generated, never hand-edited: change src/server/notion/schema.ts and re-run.
 */
export {};

import { writeFileSync } from "node:fs";
import {
  SCHEMA,
  SECOND_PASS_RELATIONS,
  RENAMED_PROPERTIES,
  type DbSpec,
  type PropSpec,
} from "../src/server/notion/schema";

const OUT = "SCHEMA.md";

/**
 * What the copy in Google Drive (Docs/stuffs-mission-control-SCHEMA.md)
 * currently contains. The Drive connector can't overwrite a file in place —
 * re-uploading mints a new link — so the copy there is refreshed in batches
 * rather than every time a field lands.
 *
 * Update these two lines whenever it IS re-uploaded. Until then this script
 * says how far behind it has drifted, so nobody has to remember.
 */
const DRIVE_COPY = { fields: 232, uploaded: "2026-07-30" };

/** Human name for a property type, plus whatever detail it carries. */
function describe(spec: PropSpec, byKey: Map<string, DbSpec>): { type: string; detail: string } {
  switch (spec.type) {
    case "relation": {
      const target = byKey.get(spec.relation ?? "");
      return { type: "relation", detail: `→ ${target?.title ?? spec.relation}` };
    }
    case "select":
    case "multi_select":
      return {
        type: spec.type,
        detail: spec.options?.length ? spec.options.join(" · ") : "free (options added on write)",
      };
    case "formula":
      return { type: "formula", detail: `\`${spec.expression ?? ""}\`` };
    default:
      return { type: spec.type, detail: "" };
  }
}

function table(db: DbSpec, byKey: Map<string, DbSpec>): string {
  const rows = Object.entries(db.properties).map(([name, spec]) => {
    const { type, detail } = describe(spec, byKey);
    return `| ${name} | ${type} | ${detail.replace(/\|/g, "\\|")} |`;
  });
  return ["| Field | Type | Detail |", "| --- | --- | --- |", ...rows].join("\n");
}

function main() {
  const byKey = new Map(SCHEMA.map((d) => [d.key, d]));
  const out: string[] = [];

  out.push("# STUFFS Mission Control — Notion schema");
  out.push("");
  out.push(
    "Generated from `src/server/notion/schema.ts` — the single source of truth the " +
      "provision script writes to Notion. Do not edit this file by hand; change the schema " +
      "and re-run `npm run schema:doc`."
  );
  out.push("");
  out.push(`Generated ${new Date().toISOString().slice(0, 10)} · ${SCHEMA.length} databases`);
  out.push("");
  out.push("## How to read this");
  out.push("");
  out.push(
    "- **Notion is the system of record.** The app is a front end over a local cache with an " +
      "explicit refresh — never a second database."
  );
  out.push(
    "- **Key** is the internal handle used in code (`cachedRecords(\"designs\")`); **Title** is " +
      "the database name in Notion. Field names below are the exact Notion property names."
  );
  out.push(
    "- Select options listed here are **pre-seeded**. Notion accepts new options on write, so " +
      "a live database may hold more than this lists."
  );
  out.push(
    "- Provisioning is idempotent: re-running it patches missing properties onto existing " +
      "databases and never creates duplicates. Adding a field here means running **Sync schema** " +
      "once after deploy."
  );
  out.push("- Every synced record carries its external IDs — that rule is not optional.");
  out.push("");

  out.push("## Databases at a glance");
  out.push("");
  out.push("| # | Key | Title | Fields |");
  out.push("| --- | --- | --- | --- |");
  SCHEMA.forEach((db, i) => {
    out.push(`| ${i + 1} | \`${db.key}\` | ${db.title} | ${Object.keys(db.properties).length} |`);
  });
  out.push("");
  out.push(
    "Order matters: databases are created in this order so a relation's target already exists " +
      "when the relation is written. Forward and self-references are patched in a second pass."
  );
  out.push("");

  for (const db of SCHEMA) {
    out.push(`## ${db.title}`);
    out.push("");
    out.push(`\`${db.key}\``);
    out.push("");
    out.push(db.description);
    out.push("");
    out.push(table(db, byKey));
    out.push("");
  }

  out.push("## Second-pass relations");
  out.push("");
  out.push(
    "Written after every database exists — self-relations and forward references. `Reverse` " +
      "names the property Notion creates on the other side of a two-way relation."
  );
  out.push("");
  out.push("| Database | Property | Target | Reverse |");
  out.push("| --- | --- | --- | --- |");
  for (const rel of SECOND_PASS_RELATIONS) {
    out.push(
      `| ${byKey.get(rel.dbKey)?.title ?? rel.dbKey} | ${rel.propName} | ${
        byKey.get(rel.targetKey)?.title ?? rel.targetKey
      } | ${rel.dual ?? "one-way"} |`
    );
  }
  out.push("");

  out.push("## Renamed properties");
  out.push("");
  out.push(
    "Applied during provisioning before new properties are patched, so a rename moves the " +
      "content instead of leaving it behind under the old name."
  );
  out.push("");
  out.push("| Database | Was | Now |");
  out.push("| --- | --- | --- |");
  for (const r of RENAMED_PROPERTIES) {
    out.push(`| ${byKey.get(r.dbKey)?.title ?? r.dbKey} | ${r.from} | ${r.to} |`);
  }
  out.push("");

  writeFileSync(OUT, out.join("\n"));
  const fields = SCHEMA.reduce((n, d) => n + Object.keys(d.properties).length, 0);
  console.log(`Wrote ${OUT} — ${SCHEMA.length} databases, ${fields} fields.`);

  const drift = fields - DRIVE_COPY.fields;
  if (drift !== 0) {
    console.log(
      `\n  ⚠ The Drive copy is ${Math.abs(drift)} field${Math.abs(drift) === 1 ? "" : "s"} ` +
        `${drift > 0 ? "behind" : "ahead"} (last uploaded ${DRIVE_COPY.uploaded}).` +
        `\n    Re-upload to Docs/ when it's worth a new link, then update DRIVE_COPY in this file.`
    );
  }
}

main();
